### ISSUE TITLE
Frontend Error

### ISSUE THREAD

**Issue by alexxB** [jonathanheilmann/ext-jh_photoswipe#2]
Hi, 
I am getting this error here:
Fatal error: Call to a member function isEnvironmentInFrontendMode() on a non-object in /var/www/clients/client1/web29/web/typo3_src-6.2.9/typo3/sysext/extbase/Classes/Service/ImageService.php on line 143

Generated in your AddJsFooterInlineCodeViewHelper when the Line 58 ($block = $this->renderChildren();) is called.

Any Idea? 

Cheers

Alex

(P.S. its the version from TER)

**Comment by alexxB** [comment]
sorry - not your Extension but our Installation.

**Comment by jonathanheilmann** [comment]
Hi,

did you resolve the issue? May you please provide some information about how you fixed this, for other people?

Cheers,

Jonathan

**Comment by alexxB** [comment]
Sure,
most people who had that problem so far did an update from 6.1.x to 6.2.3.
For them clearing all caches in the install tool and in /typo3temp helped.

For us updating from 6.2.9 to 6.2.14 did the job.

Cheers  & thanx

Alex
