### ISSUE TITLE
Support of TYPO3 6.2 and PHP 5.3+

### ISSUE THREAD

**Issue by dogawaf** [jonathanheilmann/ext-jh_photoswipe#27]
Hello

Because of this extension support TYPO3 6.2, it should also support PHP 5.3.7+, which is the version of PHP officially supported by TYPO3 6.2
Actually, I can't run this extension on a TYPO3 6.2+PHP 5.4 because of some `::class` usage.

What do you think?

**Comment by jonathanheilmann** [comment]
By now TYPO3 6.2 LTS ran out of support, thus I won't make this changes. I'm sorry.
